### ISSUE TITLE
Set the default perl setting locale to C

### ISSUE THREAD

**Issue by sminot** [BioContainers/containers#206] opened 2018-02-20 18:53 UTC
I was just using the Prokka biocontainer, and I ran into a bug with the following error message:

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = "en_US:",
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

I found that I could fix this by running `export LC_ALL=C` immediately after invoking the docker image, before running my command of interest. In my own Docker images, I find that an easier way to fix this is to include the following line at the beginning of the build: `ENV LC_ALL C`

**Comment by bgruening** [comment] 2018-02-20 21:19
@sminot can you provide me with the exact command you run that generate this error? It seems to be some program that gets called by prokka. Would be interesting to know which one that is.

**Comment by sminot** [comment] 2018-02-20 21:22
I think it's `barrnap`. That was the error when I tried to run the full command, and I can recapitulate the error by just invoking `barrnap`.

```
>singularity exec prokka-1.12--4.img barrnap\

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = "en_US:",
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Synopsis:
  barrnap 0.8 - rapid ribosomal RNA prediction
Author:
  Torsten Seemann <torsten.seemann@gmail.com>
Usage:
  barrnap [options] <chromosomes.fasta>
Options:
  --help            This help
  --version         Print version and exit
  --citation        Print citation for referencing barrnap
  --kingdom [X]     Kingdom: bac euk mito arc (default 'bac')
  --quiet           No screen output (default OFF)
  --threads [N]     Number of threads/cores/CPUs to use (default '8')
  --lencutoff [n.n] Proportional length threshold to label as partial (default '0.8')
  --reject [n.n]    Proportional length threshold to reject prediction (default '0.5')
  --evalue [n.n]    Similarity e-value cut-off (default '1e-06')
  --incseq          Include FASTA input sequences in GFF3 output (default OFF)
```

**Comment by bgruening** [comment] 2018-02-20 21:56
Oh cool a singularity user! How cool is this! :)
I could try to patch barrnap or we could try to suppress these kind of warnings. Its a warning correct? its not an error?

**Comment by sminot** [comment] 2018-02-20 22:16
My experience is that adding `ENV LC_ALL C` to the Dockerfile fixes this error, without causing any additional problems

**Comment by bgruening** [comment] 2018-03-04 10:14
This seems to be an upstream issue which should be fixed already: https://github.com/tseemann/prokka/commit/4f4184f9f00bb387b37ad2f1ebbbb1ce5b4e9107

Can you check if you find this code in your Docker?

ping @tseemann

**Comment by mvdbeek** [comment] 2018-12-19 18:30
Sorry for digging up old thread, but I've run into a similar issue with the quast container. The problem is that there are no locales at all in the busybox container, so even setting LANG to `C.UTF-8` doesn't seem to work. What did work was mounting in /usr/lib/locale like so:
```
singularity -s exec -B /usr/lib/locale/:/usr/lib/locale/  docker://quay.io/biocontainers/quast:5.0.2--py35pl526ha92aebf_0 python -c "open('file_with_unicode_chars.txt').read()"
```

without this hack I'd see:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```

**Closed as completed** 2020-12-14 22:36 UTC
